# Generated by Django 5.0.4 on 2024-06-13 08:55

import main.utils
import product.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created date, time",
                        null=True,
                        verbose_name="Created date, time",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date, time",
                        null=True,
                        verbose_name="Created date, time",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product Name",
                        max_length=128,
                        null=True,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[(0, "SMARTPHONE"), (1, "LAPTOP")],
                        help_text="Product Category",
                        max_length=32,
                        verbose_name="Product Category",
                    ),
                ),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Product Price",
                        verbose_name="Product Price",
                    ),
                ),
                (
                    "mount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mount of products on stock",
                        verbose_name="Mount of products on stock",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Product is saling or not",
                        verbose_name="Product is saling or not",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        help_text="Product Image",
                        null=True,
                        upload_to=product.models.product.define_product_image_path,
                        validators=[main.utils.image_file_extension_validator],
                        verbose_name="Product Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
            },
        ),
    ]
