# Generated by Django 5.0.4 on 2024-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "NO_CATEGORY"), (1, "SMARTPHONE"), (2, "LAPTOP")],
                default=0,
                help_text="Product Category",
                verbose_name="Product Category",
            ),
        ),
    ]
