# Generated by Django 5.0.4 on 2024-06-13 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sum",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sum that was paid by user for order",
                        verbose_name="Sum that was paid by user for order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date, time when order was placed, finished.",
                        verbose_name="Date, time when order was placed, finished.",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            (0, "NEW"),
                            (1, "PACKED"),
                            (2, "DELIVERED"),
                            (3, "CANCELED"),
                        ],
                        help_text="Delivery Status",
                        max_length=32,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How much product items was in order",
                        verbose_name="How much product items was in order",
                    ),
                ),
                (
                    "purchase_price",
                    models.PositiveIntegerField(
                        help_text="How much paid user for one product item on pruchase moment",
                        verbose_name="How much paid user for one product item on pruchase moment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Purchased product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.product",
                        verbose_name="Purchased product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who buy products",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who buy products",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrderItem",
                "verbose_name_plural": "OrderItem",
                "db_table": "order_items",
            },
        ),
    ]
