# Generated by Django 5.0.4 on 2024-06-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="product",
            field=models.ForeignKey(
                help_text="Purchased product",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="Purchased product",
            ),
        ),
    ]
