# Generated by Django 5.0.4 on 2024-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderitems_order_alter_orderitems_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[(0, "NEW"), (1, "DELIVERED"), (2, "LAPTOP")],
                default=0,
                help_text="Delivery Status",
                max_length=32,
                verbose_name="Delivery Status",
            ),
        ),
    ]
